name: 'block_scan'
mysql:
  host: ''
  db: 'aias'
  password: 'aias.yyds'
  user: 'aias'
api: ''
start_block: 25823050
net:
  http_host: "0.0.0.0"
  http_port: 5656
  ws_host: "0.0.0.0"
  ws_port: 5757
